### ISSUE TITLE
Log an ERROR when a provided argument does not exist in the config

### ISSUE THREAD

**Issue by AlianBenabdallah** [sgoudham/mdbook-template#5]
When an argument does not exist in the template config, nothing is logged.
e.g.:
__template.md__
```
my_config [[#arg1]]
```
Using `{{#template template.md arg1=foo arg2=bar}}` does not log an error and the user is not aware of his mistake.

I propose to log an error in this case. It can be useful to identify broken templates and build CI jobs.

**Comment by sgoudham** [comment]
Hey @AlianBenabdallah, thanks for bringing my attention to this! 

That sounds like a pretty helpful error to have. Unfortunately, I won't have the time to work on this. I'd happily accept a PR if you are willing to go ahead and implement this! Of course, I'd happily try to answer any questions you might have.

**Comment by AlianBenabdallah** [comment]
Thank you for your answer ! 

I don't have the access rights to open a new PR. If possible, could you make the function `replace_args` and every struct / trait in `utils.rs` public ?

**Comment by sgoudham** [comment]
I'm not sure what you mean, sorry. If you forked the repository, you should just be able to raise a PR? 
Can you explain the reasoning behind making the functions/traits public? Thanks!

**Comment by AlianBenabdallah** [comment]
Thank you, I realized I could open the PR.

We are working on integrating `mdbook-template` to our website. We have a bunch of templates representing CLI commands. We want to implement a CI job to : 
1. Identify every `{{#template ...}}` in the guide.
2. Replace it by the actual content with `replace_template()`
3. Check that the CLI command can be parsed. 

We faced many problem because of what I previously mentionned in this issue. We also want to perform additional checks. In order to do that, we need a `FileReader` and `replace_template()`.

**Comment by sgoudham** [comment]
Ah no worries, I didn't realise people would be using the functionality itself. Will review the PR now 👍

**Comment by sgoudham** [comment]
Merged #6 for your convenience! @AlianBenabdallah

**Comment by AlianBenabdallah** [comment]
Awesome, thank you so much !
